name = "flightsabove"
main = "worker.js"
compatibility_date = "2026-02-04"

[vars]
AERODATA_HOST = "aerodatabox.p.rapidapi.com"

# Secrets configured in Cloudflare dashboard / wrangler secret put:
# AERODATA_KEY
# OPENSKY_CLIENT_ID
# OPENSKY_CLIENT_SECRET
