name = "flightsabove"
main = "worker.js"
compatibility_date = "2026-02-04"

[vars]
AERODATA_DAILY_BUDGET = "400"
ADBX_MAX_PER_DAY = "400"
ADBX_MAX_PER_HOUR = "120"
ADBX_NIGHT_MAX_PER_DAY = "400"
ADBX_NIGHT_MAX_PER_HOUR = "120"

AERODATA_HOST = "aerodatabox.p.rapidapi.com"

# Secrets configured via:
# wrangler secret put AERODATA_KEY
# wrangler secret put OPENSKY_CLIENT_ID
# wrangler secret put OPENSKY_CLIENT_SECRET